import { RenovationStyle, StyleCategory } from "@/types";

export const RENOVATION_STYLES: RenovationStyle[] = [
  // === 悦己舒适 (Emotional Healing) ===
  {
    id: "nordic",
    name: "北欧风",
    nameEn: "Nordic",
    description: "木质温润感与极简功能性，营造 hygge 式的温暖治愈空间",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=300&fit=crop",
    baseCost: 2000,
    costRange: [1600, 2500],
    promptKeywords: "Scandinavian interior design, warm wood tones, cozy textiles, functional beauty, hygge atmosphere, natural light, soft wool throws",
    lightingMaterial: "warm pendant lighting, white oak flooring, wool throw blankets, sheepskin rugs, light birch furniture, soft linen curtains",
    commercialAnchor: "IKEA BESTA system, Fritz Hansen chairs, Louis Poulsen PH lamp, Kahrs oak flooring, Marimekko textiles",
    categoryId: "emotional-healing",
  },
  {
    id: "creamy",
    name: "奶油风",
    nameEn: "Creamy Style",
    description: "柔和色调与曲面设计，提供极致的情绪抚慰与视觉温柔",
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=400&h=300&fit=crop",
    baseCost: 2200,
    costRange: [1800, 2800],
    promptKeywords: "creamy warm interior, soft beige palette, curved furniture, rounded edges, gentle tones, plush upholstery, cozy minimalist",
    lightingMaterial: "warm diffused globe lighting, cream plaster walls, boucle fabric sofa, travertine coffee table, soft wool carpet, ivory linen drapes",
    commercialAnchor: "CB2 curved sofa, West Elm boucle chairs, Zara Home textiles, Farrow & Ball Setting Plaster paint, Hay Pao lamp",
    categoryId: "emotional-healing",
  },
  {
    id: "japandi",
    name: "新日式",
    nameEn: "Japandi",
    description: "北欧简约与日式质朴的融合，追求极致的安静与禅意",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&h=300&fit=crop",
    baseCost: 2100,
    costRange: [1700, 2600],
    promptKeywords: "Japandi interior design, Japanese minimalism meets Scandinavian, natural materials, zen simplicity, tatami elements, shoji screens, warm neutrals",
    lightingMaterial: "rice paper pendant lighting, light ash wood flooring, washi paper screens, raw ceramic vessels, bamboo accents, undyed linen",
    commercialAnchor: "MUJI storage systems, Karimoku Case furniture, Isamu Noguchi Akari lamp, Kettal bamboo pieces, Fog Linen textiles",
    categoryId: "emotional-healing",
  },

  // === 经典永恒 (Classics & Status) ===
  {
    id: "minimalist",
    name: "极简主义",
    nameEn: "Minimalist",
    description: "线条素雅，注重空间感和理性逻辑，少即是多的哲学",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    baseCost: 1800,
    costRange: [1500, 2200],
    promptKeywords: "minimalist interior design, clean lines, neutral palette, open space, uncluttered, geometric precision, monochromatic elegance",
    lightingMaterial: "recessed LED ambient lighting, matte white walls, polished concrete floor, natural oak wood accents, floor-to-ceiling glass",
    commercialAnchor: "Benjamin Moore Simply White paint, HAY furniture, Flos IC lighting, Dinesen Douglas fir flooring",
    categoryId: "classics-status",
  },
  {
    id: "french-vintage",
    name: "法式复古",
    nameEn: "French Vintage",
    description: "精致线条与复古家具，巴黎左岸式的优雅阶层认同",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&h=300&fit=crop",
    baseCost: 2800,
    costRange: [2400, 3500],
    promptKeywords: "French vintage interior, Parisian apartment, ornate molding, herringbone parquet, velvet upholstery, antique brass, classical elegance",
    lightingMaterial: "crystal chandelier warm lighting, gilded mirror reflections, marble fireplace, silk drapes, chevron oak parquet, crown molding",
    commercialAnchor: "Farrow & Ball Elephants Breath paint, Maison du Monde furniture, Visual Comfort chandelier, Versailles parquet flooring",
    categoryId: "classics-status",
  },
  {
    id: "modern-luxury",
    name: "意式轻奢",
    nameEn: "Modern Luxury",
    description: "石材与金属质感的交响，拉高空间视觉阶层的优雅奢华",
    image: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=400&h=300&fit=crop",
    baseCost: 3200,
    costRange: [2800, 4000],
    promptKeywords: "Italian modern luxury interior, marble surfaces, brushed gold accents, rich textures, statement lighting, sophisticated palette, high-end finishes",
    lightingMaterial: "sculptural brass chandelier, Calacatta marble countertops, smoked glass partitions, velvet emerald accents, polished travertine floor",
    commercialAnchor: "Minotti sofa, Fendi Casa accessories, Tom Dixon lighting, Calacatta marble, Poliform kitchen, Molteni wardrobe systems",
    categoryId: "classics-status",
  },

  // === 艺术先锋 (Avant-Garde) ===
  {
    id: "industrial",
    name: "工业风",
    nameEn: "Industrial",
    description: "金属、水泥与裸露管线，粗犷硬朗的都市美学宣言",
    image: "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=400&h=300&fit=crop",
    baseCost: 1600,
    costRange: [1200, 2000],
    promptKeywords: "industrial loft interior, exposed brick, metal pipes, concrete floors, Edison bulbs, raw materials, urban aesthetic, steel beams",
    lightingMaterial: "exposed Edison bulb pendant lights, exposed brick walls, polished concrete floor, black steel frame windows, leather upholstery, copper pipes",
    commercialAnchor: "Restoration Hardware furniture, Schoolhouse Electric fixtures, Armstrong VCT flooring, Crittall steel windows",
    categoryId: "avant-garde",
  },
  {
    id: "bauhaus",
    name: "包豪斯",
    nameEn: "Bauhaus",
    description: "纯粹功能主义与几何构图，理性精英的空间美学信条",
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=400&h=300&fit=crop",
    baseCost: 2400,
    costRange: [2000, 3000],
    promptKeywords: "Bauhaus interior design, geometric forms, primary color accents, functional minimalism, tubular steel furniture, rational design, grid systems",
    lightingMaterial: "Bauhaus globe pendant lights, white plaster walls, primary color accent walls, tubular steel chairs, geometric tile patterns, terrazzo floor",
    commercialAnchor: "Knoll Barcelona chair, Tecnolumen Bauhaus lamp, USM Haller modular system, Vitra design furniture, Bauhaus archive inspired",
    categoryId: "avant-garde",
  },
  {
    id: "pop-art",
    name: "波普艺术",
    nameEn: "Pop Art",
    description: "大胆色彩碰撞与视觉冲击，年轻活力的个性化表达",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=300&fit=crop",
    baseCost: 2000,
    costRange: [1600, 2500],
    promptKeywords: "Pop Art interior design, bold color blocking, graphic patterns, vibrant accents, statement art, playful design, Roy Lichtenstein inspired, Memphis Milano",
    lightingMaterial: "neon accent lighting, bold colored walls, graphic print wallpaper, acrylic furniture, terrazzo flooring, chrome accents, oversized artwork",
    commercialAnchor: "Kartell ghost chairs, Memphis Milano design, Seletti lighting, KAWS art pieces, Verner Panton chairs, Missoni Home textiles",
    categoryId: "avant-garde",
  },

  // === 文化底蕴 (Heritage & Zen) ===
  {
    id: "new-chinese",
    name: "新中式",
    nameEn: "New Chinese",
    description: "传统底蕴与现代材质的重构，理性内敛的东方美学",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=400&h=300&fit=crop",
    baseCost: 3000,
    costRange: [2500, 3800],
    promptKeywords: "modern Chinese interior design, oriental elegance, silk screens, lacquer furniture, bamboo elements, zen garden view, ink wash aesthetic",
    lightingMaterial: "paper lantern ambient lighting, rosewood furniture, silk wall panels, celadon ceramic vases, ink wash painting backdrop, bamboo partitions",
    commercialAnchor: "Stellar Works furniture, BANMOO design, Zhu Xiaojie lacquerware, Dehua porcelain, Suzhou silk wallcovering",
    categoryId: "heritage-zen",
  },
  {
    id: "wabi-sabi",
    name: "侘寂风",
    nameEn: "Wabi-Sabi",
    description: "原生态材质与不完美的艺术，自然秩序的返璞归真",
    image: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=400&h=300&fit=crop",
    baseCost: 2200,
    costRange: [1800, 2800],
    promptKeywords: "wabi-sabi interior, imperfect beauty, organic textures, earth tones, handcrafted pottery, natural linen, weathered surfaces, raw plaster",
    lightingMaterial: "soft diffused natural light, lime-washed walls, raw wood beams, unglazed ceramic, linen curtains, stone basin, hand-troweled plaster",
    commercialAnchor: "Marrakech Design tiles, MUJI storage, Noguchi Akari lamp, Axel Vervoordt inspired plaster walls, Astier de Villatte ceramics",
    categoryId: "heritage-zen",
  },
  {
    id: "moroccan",
    name: "摩洛哥风",
    nameEn: "Moroccan Exotic",
    description: "复杂几何拼花与浓郁色调，异域神秘的空间叙事",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=400&h=300&fit=crop",
    baseCost: 2600,
    costRange: [2200, 3200],
    promptKeywords: "Moroccan interior design, zellige tiles, geometric patterns, jewel tones, carved plaster, brass lanterns, arched doorways, vibrant textiles",
    lightingMaterial: "pierced brass lantern lighting, zellige mosaic tiles, tadelakt plaster walls, jewel-toned velvet cushions, carved cedar screens, mosaic fountain",
    commercialAnchor: "Popham Design tiles, Moroccan Bazaar brass fixtures, Caravane textiles, Beni Ourain rugs, Tazi Designs furniture",
    categoryId: "heritage-zen",
  },
];

export const STYLE_CATEGORIES: StyleCategory[] = [
  {
    id: "emotional-healing",
    name: "悦己舒适",
    nameEn: "Emotional Healing",
    description: "治愈与感性回归",
    styles: RENOVATION_STYLES.filter((s) => s.categoryId === "emotional-healing"),
  },
  {
    id: "classics-status",
    name: "经典永恒",
    nameEn: "Classics & Status",
    description: "阶层认同与商业溢价",
    styles: RENOVATION_STYLES.filter((s) => s.categoryId === "classics-status"),
  },
  {
    id: "avant-garde",
    name: "艺术先锋",
    nameEn: "Avant-Garde",
    description: "个性表达与精英意识",
    styles: RENOVATION_STYLES.filter((s) => s.categoryId === "avant-garde"),
  },
  {
    id: "heritage-zen",
    name: "文化底蕴",
    nameEn: "Heritage & Zen",
    description: "精神归宿与审美深度",
    styles: RENOVATION_STYLES.filter((s) => s.categoryId === "heritage-zen"),
  },
];
